# ============================================================
# ROBOT SELF KNOWLEDGE
# ============================================================
#
# Selective robot knowledge system.
#
# This file DOES NOT directly answer user questions.
#
# It:
#
# 1. Stores the authoritative architecture of Master.
# 2. Divides that architecture into categories.
# 3. Uses a small Groq routing request to determine whether
#    a question is about Master.
# 4. Determines which knowledge categories are required.
# 5. Determines whether live CV/person information is needed.
#
# The final answer is generated by robot_conversation.py.
# ============================================================

import os
import json

from dotenv import load_dotenv
from groq import Groq


# ============================================================
# SETUP
# ============================================================

load_dotenv()

GROQ_API_KEY = os.getenv(
    "GROQ_API_KEY"
)

if not GROQ_API_KEY:
    raise ValueError(
        "GROQ_API_KEY not found in .env"
    )

client = Groq(
    api_key=GROQ_API_KEY
)


# ============================================================
# ROBOT KNOWLEDGE DATABASE
# ============================================================
#
# IMPORTANT:
# Keep information here factual to the actual robot.
#
# Categories are intentionally separated so that only the
# required category is sent to the final AI.
# ============================================================

ROBOT_KNOWLEDGE = {

    # --------------------------------------------------------
    # IDENTITY
    # --------------------------------------------------------

    "identity": """
Robot name: Master.

Robot type:
Humanoid robot head.

Creator / developer:
VS Tech Horizon.

Purpose:
The robot is designed for human interaction using speech,
artificial intelligence, computer vision and robotic movement.

Wake word:
Hey Master.
""",

    # --------------------------------------------------------
    # LANGUAGES
    # --------------------------------------------------------

    "language": """
Supported languages:
- English
- Hindi
- Marathi

Speech language detection:
Lingua.

Speech recognition:
Groq Whisper.

The detected user language is passed through the conversation
pipeline.

The robot responds in the detected language.
""",

    # --------------------------------------------------------
    # AUDIO / HEARING
    # --------------------------------------------------------

    "audio": """
The robot uses a USB audio device for voice interaction.

Input:
USB microphone.

Output:
USB speaker.

Speech recognition:
Groq Whisper.

The microphone captures the user's speech and the speech
recognition system converts it into text.
""",

    # --------------------------------------------------------
    # SPEECH / TTS
    # --------------------------------------------------------

    "speech": """
The robot generates spoken responses using its text-to-speech
system.

The response language follows the detected user language.

The generated speech is played through the robot's speaker.

During robot speech, the jaw movement system analyzes the audio
signal and synchronizes jaw movement with speech.
""",

    # --------------------------------------------------------
    # CAMERA
    # --------------------------------------------------------

    "camera": """
Camera type:
USB camera.

Camera resolution:
640 x 480 pixels.

Camera index:
0.

Physical location:
Inside the robot's left eye.

The camera provides the visual input used by the computer
vision system.
""",

    # --------------------------------------------------------
    # COMPUTER VISION
    # --------------------------------------------------------

    "vision": """
The robot has a computer vision system.

Main computer vision components:
- YOLO
- MediaPipe
- InsightFace

Computer vision capabilities include:
- face detection
- face position detection
- people detection
- people counting
- object detection
- closest-person target selection
- stable target tracking
- head horizontal direction
- head vertical direction
- head tilt
- gaze information
- face recognition

The camera is mounted inside the moving head/left eye, so the
vision system also provides the information used for eye and
neck tracking.
""",

    # --------------------------------------------------------
    # FACE RECOGNITION
    # --------------------------------------------------------

    "face_recognition": """
Face recognition uses InsightFace.

The robot can recognize registered/known faces.

The system maintains known-face information.

The robot also supports face enrollment, allowing a person's
face to be registered with a name.

Current recognition results are separate from the permanent
robot architecture and are supplied as live information when
required.
""",

    # --------------------------------------------------------
    # OBJECT DETECTION
    # --------------------------------------------------------

    "object_detection": """
Object detection is performed using YOLO.

The vision system can detect objects visible in the camera
view.

Object information is treated as live camera information.
The complete list of currently visible objects is not permanent
robot knowledge and is fetched only when a question requires it.
""",

    # --------------------------------------------------------
    # PEOPLE DETECTION / TRACKING
    # --------------------------------------------------------

    "people_tracking": """
The computer vision system can detect people.

It supports:
- people detection
- people counting
- closest-person selection
- stable target identification
- person tracking

Live information about how many people are currently visible
or which person is currently being tracked is fetched only
when required.
""",

    # --------------------------------------------------------
    # HEAD / FACE ANALYSIS
    # --------------------------------------------------------

    "head_tracking": """
The MediaPipe vision system provides face landmark information.

The robot can estimate:
- horizontal face position
- vertical face position
- head horizontal direction
- head vertical direction
- head tilt
- gaze

These values are live camera information and are retrieved only
when the user's question requires them.
""",

    # --------------------------------------------------------
    # EYES
    # --------------------------------------------------------

    "eyes": """
The robot has eye movement controlled through servo motors.

Horizontal eye movement:
45 degrees = robot right
90 degrees = center
135 degrees = robot left

Vertical eye movement:
90 degrees = up
135 degrees = center
180 degrees = down

The eye system uses camera-based face tracking.

The camera detects the face position and the control system
converts that information into eye movement commands.
""",

    # --------------------------------------------------------
    # NECK
    # --------------------------------------------------------

    "neck": """
The robot has a neck servo for horizontal head rotation.

The neck is used together with camera-based face tracking.

The camera is mounted inside the moving head, so the tracking
controller uses a hierarchical eye -> neck -> eye tracking
architecture.

The current control architecture uses incremental neck movement,
hysteresis and confirmation logic to reduce oscillation and
overshoot.
""",

    # --------------------------------------------------------
    # JAW
    # --------------------------------------------------------

    "jaw": """
The robot has a jaw servo.

The jaw is controlled independently from camera tracking.

During speech, the audio signal is analyzed using amplitude/RMS
information.

Jaw positions used by the audio synchronization system include:
45 degrees = closed
90 degrees = middle
120 degrees = open

The jaw movement is synchronized with the robot's speech.
""",

    # --------------------------------------------------------
    # SERVO SYSTEM
    # --------------------------------------------------------

    "servos": """
The robot has four servo-controlled movement functions:

1. Horizontal eye movement
2. Vertical eye movement
3. Neck movement
4. Jaw movement

The Raspberry Pi does not directly drive the servo motors.

Servo commands are sent through MQTT to the ESP32, which
controls the servo hardware.
""",

    # --------------------------------------------------------
    # RASPBERRY PI
    # --------------------------------------------------------

    "raspberry_pi": """
The Raspberry Pi is the main controller of the humanoid robot
head.

The Raspberry Pi handles the main software systems including:
- voice processing
- language detection
- AI conversation
- computer vision
- face recognition
- robot response generation
- TTS coordination
- MQTT communication
- camera-based servo control

The current robot uses a Raspberry Pi 4 Model B.
""",

    # --------------------------------------------------------
    # ESP32
    # --------------------------------------------------------

    "esp32": """
An ESP32 is used as the servo-side controller.

The Raspberry Pi sends servo commands to the ESP32.

The ESP32 controls:
- horizontal eye servo
- vertical eye servo
- neck servo
- jaw servo
""",

    # --------------------------------------------------------
    # MQTT
    # --------------------------------------------------------

    "mqtt": """
The Raspberry Pi communicates with the ESP32 using MQTT.

MQTT is used for the four servo command channels:

Jaw:
humanoid_robot_piyusha/jaw

Horizontal eye:
humanoid_robot_piyusha/eye_horizontal

Vertical eye:
humanoid_robot_piyusha/eye_vertical

Neck:
humanoid_robot_piyusha/neck
""",

    # --------------------------------------------------------
    # AI
    # --------------------------------------------------------

    "ai": """
The robot uses an AI conversation system running through Groq.

The AI is used to:
- understand user questions
- generate natural responses
- use selected robot self-knowledge
- use selected live CV information when required
- use person information when required
- use web search when current/external information is required

The robot's final response is generated in the detected user
language.
""",

    # --------------------------------------------------------
    # MEMORY
    # --------------------------------------------------------

    "memory": """
The robot maintains conversation history.

It also maintains a known-face system for registered people.

Face enrollment allows a person's face to be associated with a
name.

Person-specific conversation history can be maintained by the
existing conversation-history system.
""",

    # --------------------------------------------------------
    # COMMUNICATION / OVERALL
    # --------------------------------------------------------

    "capabilities": """
Master is a humanoid robot head developed by VS Tech Horizon.

Major capabilities include:
- multilingual speech interaction
- English, Hindi and Marathi communication
- speech recognition
- text-to-speech
- computer vision
- face detection
- face recognition
- people detection
- people counting
- object detection
- target tracking
- head direction estimation
- head tilt estimation
- gaze estimation
- eye movement
- neck movement
- speech-synchronized jaw movement
- AI conversation
- face enrollment
- MQTT communication with an ESP32
"""
}

# ============================================================
# SELECTIVE KNOWLEDGE RETRIEVAL
# ============================================================

def get_knowledge(categories):
    """
    Return only the robot self-knowledge
    required for the requested categories.
    """

    if not categories:
        return ""

    selected = []

    for category in categories:

        if category in ROBOT_KNOWLEDGE:

            selected.append(
                f"[{category}]\n"
                + ROBOT_KNOWLEDGE[category].strip()
            )

    return "\n\n".join(selected)
# ============================================================
# CATEGORY DESCRIPTIONS FOR THE ROUTER
# ============================================================
#
# Keep this list small.
# The complete knowledge is NOT sent to the router.
# ============================================================

CATEGORY_DESCRIPTIONS = {

    "identity":
        "name, creator, robot type, purpose, wake word",

    "language":
        "spoken languages, language detection, multilingual behavior",

    "audio":
        "microphone, hearing, audio input",

    "speech":
        "speaker, speech generation, TTS, speaking behavior",

    "camera":
        "camera type, resolution, physical camera location",

    "vision":
        "computer vision architecture and general visual capabilities",

    "face_recognition":
        "face recognition, registered faces, face enrollment",

    "object_detection":
        "YOLO and object detection",

    "people_tracking":
        "people detection, people counting, target tracking",

    "head_tracking":
        "head direction, head tilt, gaze, face position",

    "eyes":
        "eye servo movement and eye tracking",

    "neck":
        "neck servo and head movement",

    "jaw":
        "jaw servo and speech synchronization",

    "servos":
        "four servo movement functions and servo architecture",

    "raspberry_pi":
        "Raspberry Pi controller and main processing",

    "esp32":
        "ESP32 servo controller",

    "mqtt":
        "MQTT communication between Raspberry Pi and ESP32",

    "ai":
        "AI, Groq and conversation architecture",

    "memory":
        "conversation history, face enrollment and stored information",

    "capabilities":
        "overall robot features and abilities"
}


# ============================================================
# ROUTER
# ============================================================

def classify_question(user_text):
    """
    Semantic router for robot self-knowledge.

    This function does NOT answer the question.
    It only determines:
        - whether the question is about Master
        - which knowledge categories are needed
        - whether live CV is required
        - whether person information is required
    """

    question = (user_text or "").strip()

    if not question:
        return {
            "is_self": False,
            "categories": [],
            "needs_live_cv": False,
            "needs_person": False
        }

    # --------------------------------------------------------
    # Keep the router prompt intentionally small.
    # --------------------------------------------------------

    system_prompt = """
You are the intent router for a humanoid robot named Master.

Your task is ONLY to classify the user's question.
Do NOT answer the question.

"is_self" means:
The user is asking about Master, Master's hardware,
software, abilities, sensors, movement, languages,
architecture, or how Master works.

Examples of SELF questions:
- What is your name?
- Who made you?
- Which languages can you speak?
- What camera do you have?
- How many servos do you have?
- How do your eyes follow me?
- Can you see me?
- Do you recognize me?
- What can you do?

Examples of NOT SELF questions:
- What is the capital of India?
- What is today's weather?
- What is the latest news?
- What is 25 times 48?

Use ONLY these categories:

identity
language
audio
speech
camera
vision
face_recognition
object_detection
people_tracking
head_tracking
eyes
neck
jaw
servos
raspberry_pi
esp32
mqtt
ai
memory
capabilities

Category meanings:

identity = robot name, creator, purpose
language = languages and language detection
audio = microphone and hearing
speech = speaking and TTS
camera = camera hardware and location
vision = computer vision system
face_recognition = recognizing or enrolling faces
object_detection = detecting objects
people_tracking = detecting/counting/tracking people
head_tracking = face position, head direction, tilt, gaze
eyes = eye movement and eye tracking
neck = neck/head movement
jaw = jaw movement and speech synchronization
servos = servo architecture
raspberry_pi = Raspberry Pi
esp32 = ESP32
mqtt = MQTT communication
ai = AI and conversation
memory = conversation/face memory
capabilities = overall abilities

Live CV:
Set needs_live_cv=true when the question requires information
about what the camera currently sees or is currently doing.

Examples:
"Can you see me?" -> true
"Do you recognize me?" -> true
"What objects can you see?" -> true
"How many people are here?" -> true

Person information:

Set needs_person=true ONLY when information about the currently
recognized person is required.

Examples:

"Can you see me?"
-> needs_person=false

"Are you looking at me?"
-> needs_person=false

"Do you recognize me?"
-> needs_person=true

"What is my name?"
-> needs_person=true
IMPORTANT:
The word "me" by itself does NOT mean needs_person=true.

Questions about whether the robot can currently see, look at,
detect, or track the user require live CV but do not require
person information.

Only questions involving identity, recognition, name, or known-person
information require needs_person=true.
IMPORTANT:
A question such as "How do your eyes follow me?"
is about Master's architecture, NOT about the current identity
of the person.

Return ONLY JSON with exactly these fields:

{
  "is_self": true or false,
  "categories": ["category1", "category2"],
  "needs_live_cv": true or false,
  "needs_person": true or false
}
"""

    user_prompt = f"""
Classify this user question:

{question}
"""

    try:

        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",

            messages=[
                {
                    "role": "system",
                    "content": system_prompt
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ],

            response_format={
                "type": "json_object"
            },

            temperature=0,

            max_completion_tokens=300
        )

        content = (
            response
            .choices[0]
            .message
            .content
        )

        print(
            "[SELF ROUTER RAW]",
            repr(content)
        )

        result = json.loads(content)

        # ----------------------------------------------------
        # VALIDATE
        # ----------------------------------------------------

        is_self = bool(
            result.get(
                "is_self",
                False
            )
        )

        categories = result.get(
            "categories",
            []
        )

        if not isinstance(
            categories,
            list
        ):
            categories = []

        # Only allow categories that actually exist
        # in our knowledge database.
        categories = [
            category
            for category in categories
            if category in ROBOT_KNOWLEDGE
        ]

        needs_live_cv = bool(
            result.get(
                "needs_live_cv",
                False
            )
        )

        needs_person = bool(
            result.get(
                "needs_person",
                False
            )
        )

        # Non-self questions cannot request robot
        # knowledge or live robot information.
        if not is_self:

            categories = []

            needs_live_cv = False

            needs_person = False

        final_result = {
            "is_self": is_self,
            "categories": categories,
            "needs_live_cv": needs_live_cv,
            "needs_person": needs_person
        }

        print(
            "[SELF ROUTER]",
            final_result
        )

        return final_result

    except Exception as e:

        print(
            "[SELF ROUTER] Error:",
            e
        )

        return {
            "is_self": False,
            "categories": [],
            "needs_live_cv": False,
            "needs_person": False
        }